#!/usr/bin/env bash
# server red

sudo apt-get -y update
sudo apt-get -y install nginx
myc="\n\trewrite \^\/redirect_me\/\$ https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent\;"
st="server {"
sudo sed -i "0,/$st/{s/$st/$st$myc/}" /etc/nginx/sites-enabled/default
sudo service nginx start
